/* AUTO-GENERATED by scripts/build-native-tokens.js — do not edit. */
/* Drop-in screen wrapper. Applies mov min page margins to content automatically. */

package com.minapps.ds.ui

import androidx.compose.foundation.layout.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.unit.dp
import com.minapps.ds.tokens.MinPageMargins

/**
 * Screen-level container that enforces the mov min (WatchedIt) page grid.
 *
 * Wrap every screen in every native min app with this. Content gets the correct
 * horizontal and vertical insets — no hard-coded padding on children.
 *
 *     MinAppLayout(header = { MinAppHeader("YourTube") }) {
 *         LazyColumn { … }
 *     }
 */
@Composable
fun MinAppLayout(
    modifier: Modifier = Modifier,
    header: @Composable (() -> Unit)? = null,
    footer: @Composable (() -> Unit)? = null,
    content: @Composable () -> Unit,
) {
    val sw = LocalConfiguration.current.screenWidthDp
    val compact = sw < 600

    val padH = if (compact) MinPageMargins.MARGIN_LEFT_MOBILE.dp else MinPageMargins.MARGIN_LEFT.dp
    val padTop = if (compact) MinPageMargins.MARGIN_TOP_MOBILE.dp else MinPageMargins.MARGIN_TOP.dp
    val padBottom = if (compact) MinPageMargins.MARGIN_BOTTOM_MOBILE.dp else MinPageMargins.MARGIN_BOTTOM.dp

    Column(modifier = modifier.fillMaxSize()) {
        header?.invoke()

        Box(
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth()
                .padding(start = padH, end = padH, top = padTop, bottom = padBottom),
            contentAlignment = Alignment.TopStart,
        ) {
            content()
        }

        footer?.invoke()
    }
}
