// AUTO-GENERATED by scripts/build-native-tokens.js — do not edit.
// Header bar with mov min page margins — matches web AppHeader.

import SwiftUI

/// Top bar for any min app screen. Uses the same padding as the content area
/// so title text and actions align with the page grid.
///
///     MinAppHeaderView("YourTube", logo: Image("yt-logo"))
///
public struct MinAppHeaderView: View {
    @Environment(\.horizontalSizeClass) private var horizontalSizeClass

    private let title: String
    private let logo: Image?
    private let actions: AnyView?

    public init(
        _ title: String,
        logo: Image? = nil,
        actions: AnyView? = nil
    ) {
        self.title = title
        self.logo = logo
        self.actions = actions
    }

    public var body: some View {
        HStack(spacing: 16) {
            if let logo {
                logo
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .frame(width: 48, height: 48)
            }

            Text(title)
                .font(.system(size: MinHeaderTitle.fontSize, weight: MinHeaderTitle.fontWeight))
                .lineLimit(1)
                .truncationMode(.tail)

            Spacer(minLength: 0)

            if let actions {
                actions
            }
        }
        .padding(.top, MinPageMargins.verticalPaddingTop(horizontalSizeClass: horizontalSizeClass))
        .padding(.bottom, MinPageMargins.verticalPaddingBottom(horizontalSizeClass: horizontalSizeClass))
        .padding(.horizontal, MinPageMargins.horizontalPadding(horizontalSizeClass: horizontalSizeClass))
    }
}
