// AUTO-GENERATED by scripts/build-native-tokens.js — do not edit.
// Drop-in screen wrapper. Applies mov min page margins to content automatically.
// Every screen in every native min app should use this.

import SwiftUI

/// Screen-level container that enforces the mov min (WatchedIt) page grid.
///
/// Wrap every screen's content in `MinAppLayout` so horizontal and vertical
/// insets match across all four apps — no hard-coded `16` or per-screen padding.
///
///     MinAppLayout {
///         List { … }
///     }
///
/// With a header:
///
///     MinAppLayout(header: { MinAppHeaderView("YourTube") }) {
///         VideoQueueList(videos)
///     }
///
public struct MinAppLayout<Header: View, Content: View>: View {
    @Environment(\.horizontalSizeClass) private var horizontalSizeClass

    private let header: Header
    private let content: Content

    public init(
        @ViewBuilder header: () -> Header,
        @ViewBuilder content: () -> Content
    ) {
        self.header = header()
        self.content = content()
    }

    public var body: some View {
        VStack(spacing: 0) {
            header

            content
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
                .padding(.top, MinPageMargins.verticalPaddingTop(horizontalSizeClass: horizontalSizeClass))
                .padding(.bottom, MinPageMargins.verticalPaddingBottom(horizontalSizeClass: horizontalSizeClass))
                .padding(.horizontal, MinPageMargins.horizontalPadding(horizontalSizeClass: horizontalSizeClass))
        }
    }
}

extension MinAppLayout where Header == EmptyView {
    /// Convenience: no header, just content with page margins.
    public init(@ViewBuilder content: () -> Content) {
        self.init(header: { EmptyView() }, content: content)
    }
}
