// AUTO-GENERATED by scripts/build-native-tokens.js — do not edit.
// Floating dismiss button positioned at mov min page offsets.

import SwiftUI

/// Floating dismiss / close button. Anchors to the bottom-leading corner using
/// `MinPageMargins` so the offset matches the page grid in every app.
///
///     ZStack(alignment: .bottomLeading) {
///         ScrollView { … }
///         MinDismissButtonView(isVisible: scrolled) { dismiss() }
///     }
///
public struct MinDismissButtonView: View {
    @Environment(\.horizontalSizeClass) private var horizontalSizeClass

    let isVisible: Bool
    let isExpanded: Bool
    let label: String
    let icon: String
    let action: () -> Void

    public init(
        isVisible: Bool = true,
        isExpanded: Bool = false,
        label: String = "Close",
        icon: String = "chevron.down",
        action: @escaping () -> Void
    ) {
        self.isVisible = isVisible
        self.isExpanded = isExpanded
        self.label = label
        self.icon = icon
        self.action = action
    }

    private var size: CGFloat { isExpanded ? 56 : 48 }

    public var body: some View {
        if isVisible {
            Button(action: action) {
                VStack(spacing: 2) {
                    Image(systemName: icon)
                        .font(.system(size: isExpanded ? 20 : 16, weight: .medium))
                    if isExpanded {
                        Text(label)
                            .font(.system(size: 10, weight: .medium))
                    }
                }
                .frame(width: size, height: size)
                .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 12))
                .shadow(color: .black.opacity(0.15), radius: 8, y: 2)
            }
            .accessibilityLabel(label)
            .padding(.leading, MinPageMargins.horizontalPadding(horizontalSizeClass: horizontalSizeClass))
            .padding(.bottom, MinPageMargins.verticalPaddingBottom(horizontalSizeClass: horizontalSizeClass))
            .transition(.move(edge: .bottom).combined(with: .opacity))
            .animation(.easeOut(duration: 0.25), value: isVisible)
        }
    }
}
