/* AUTO-GENERATED by scripts/build-native-tokens.js — do not edit. */
/* Floating dismiss button positioned at mov min page offsets. */

package com.minapps.ds.ui

import androidx.compose.animation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.KeyboardArrowDown
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.minapps.ds.tokens.MinPageMargins

/**
 * Floating dismiss / close button anchored to the bottom-start corner at
 * mov min page offsets.
 *
 *     Box(modifier = Modifier.fillMaxSize()) {
 *         LazyColumn { … }
 *         MinDismissButton(
 *             visible = scrolled,
 *             onClick = { dismiss() },
 *             modifier = Modifier.align(Alignment.BottomStart),
 *         )
 *     }
 */
@Composable
fun MinDismissButton(
    visible: Boolean,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    expanded: Boolean = false,
    label: String = "Close",
) {
    val sw = LocalConfiguration.current.screenWidthDp
    val compact = sw < 600

    val padH = if (compact) MinPageMargins.MARGIN_LEFT_MOBILE.dp else MinPageMargins.MARGIN_LEFT.dp
    val padBottom = if (compact) MinPageMargins.MARGIN_BOTTOM_MOBILE.dp else MinPageMargins.MARGIN_BOTTOM.dp
    val size = if (expanded) 56.dp else 48.dp

    AnimatedVisibility(
        visible = visible,
        enter = slideInVertically(initialOffsetY = { it }) + fadeIn(),
        exit = slideOutVertically(targetOffsetY = { it }) + fadeOut(),
        modifier = modifier.padding(start = padH, bottom = padBottom),
    ) {
        ElevatedButton(
            onClick = onClick,
            modifier = Modifier.size(size),
            shape = RoundedCornerShape(12.dp),
            contentPadding = PaddingValues(0.dp),
        ) {
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                Icon(
                    imageVector = Icons.Filled.KeyboardArrowDown,
                    contentDescription = null,
                    modifier = Modifier.size(if (expanded) 24.dp else 20.dp),
                )
                if (expanded) {
                    Text(text = label, fontSize = 10.sp)
                }
            }
        }
    }
}
