/* AUTO-GENERATED by scripts/build-native-tokens.js — do not edit. */
/* Source: src/tokens/spacing.js (spacing.page). Re-run: npm run build:native */

package com.minapps.ds.tokens

/**
 * Page insets for every min app — same grid as WatchedIt (mov min).
 * Values are **dp** (Compose / resource qualifiers). Apply as padding on root scaffold,
 * RecyclerView padding, search/filter rows, and floating actions so vid/pod/cyc match mov min.
 */
object MinPageMargins {
    const val MARGIN_TOP = 24
    const val MARGIN_BOTTOM = 24
    const val MARGIN_LEFT = 24
    const val MARGIN_RIGHT = 24
    const val MARGIN_TOP_MOBILE = 16
    const val MARGIN_BOTTOM_MOBILE = 16
    const val MARGIN_LEFT_MOBILE = 16
    const val MARGIN_RIGHT_MOBILE = 16
}
