// AUTO-GENERATED by scripts/build-native-tokens.js — do not edit.
// Source: src/tokens/minTitles.js. Re-run: npm run build:native

import SwiftUI

// MARK: - Constants

/// Primary title in the main content column (detail / show hero).
/// Leading edge must align with `MinPageMargins`; do not invent separate horizontal inset.
public enum MinMainContentTitle {
    public static let fontSize: CGFloat = 48
    public static let fontWeight: Font.Weight = .bold
    public static let lineHeightMultiple: CGFloat = 1.2000
    public static let letterSpacingPoints: CGFloat = -1.2
    public static let marginBottom: CGFloat = 16
}

/// Home screen app name (centered).
/// Use `fontSizeCompact` when width is compact (~<768pt) to match the 767px breakpoint.
public enum MinHomeScreenTitle {
    public static let fontSizeRegular: CGFloat = 36
    public static let fontSizeCompact: CGFloat = 30
    public static let fontWeight: Font.Weight = .bold
    public static let lineHeightMultipleRegular: CGFloat = 1.2500
    public static let lineHeightMultipleCompact: CGFloat = 1.3000
    public static let letterSpacingPointsRegular: CGFloat = -0.9
    public static let letterSpacingPointsCompact: CGFloat = -0.75
    public static let marginBottom: CGFloat = 8
}

/// Top bar / navigation title next to back chevron or logo.
public enum MinHeaderTitle {
    public static let fontSize: CGFloat = 20
    public static let fontWeight: Font.Weight = .semibold
    public static let lineHeightMultiple: CGFloat = 1.4000
}

// MARK: - SwiftUI Views

/// Primary title for movie detail, podcast show, video, race hero — same size and position across every min app.
///
/// Parent must already apply `MinPageMargins` horizontal padding so the leading edge lines up
/// with lists, search, and `MinMainAppLoadingView`.
///
///     ScrollView {
///         MinMainContentTitleView(movie.title)
///         // … rest of detail content
///     }
///     .padding(.horizontal, MinPageMargins.horizontalPadding(horizontalSizeClass: hsc))
///
public struct MinMainContentTitleView: View {
    private let text: String
    private let bottomSpacing: CGFloat

    public init(_ text: String, bottomSpacing: CGFloat = MinMainContentTitle.marginBottom) {
        self.text = text
        self.bottomSpacing = bottomSpacing
    }

    public var body: some View {
        Text(text)
            .font(.system(size: MinMainContentTitle.fontSize, weight: MinMainContentTitle.fontWeight))
            .tracking(MinMainContentTitle.letterSpacingPoints)
            .lineSpacing((MinMainContentTitle.fontSize * MinMainContentTitle.lineHeightMultiple) - MinMainContentTitle.fontSize)
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.bottom, bottomSpacing)
            .accessibilityAddTraits(.isHeader)
    }
}

/// Home screen app name — centered, bold, compact-aware. Drop in at the top of the home
/// `ScrollView` after the logo/artwork asset.
///
///     MinHomeScreenTitleView("WatchedIt")
///
public struct MinHomeScreenTitleView: View {
    @Environment(\.horizontalSizeClass) private var horizontalSizeClass

    private let text: String
    private let bottomSpacing: CGFloat

    public init(_ text: String, bottomSpacing: CGFloat = MinHomeScreenTitle.marginBottom) {
        self.text = text
        self.bottomSpacing = bottomSpacing
    }

    private var isCompact: Bool {
        MinPageMargins.useCompactPageMargins(horizontalSizeClass: horizontalSizeClass)
    }

    public var body: some View {
        Text(text)
            .font(.system(
                size: isCompact ? MinHomeScreenTitle.fontSizeCompact : MinHomeScreenTitle.fontSizeRegular,
                weight: MinHomeScreenTitle.fontWeight
            ))
            .tracking(isCompact ? MinHomeScreenTitle.letterSpacingPointsCompact : MinHomeScreenTitle.letterSpacingPointsRegular)
            .multilineTextAlignment(.center)
            .frame(maxWidth: .infinity)
            .padding(.bottom, bottomSpacing)
            .accessibilityAddTraits(.isHeader)
    }
}

/// Inline navigation / top-bar title. Use inside a custom header `HStack` or as the
/// `navigationTitle` equivalent when you own the chrome.
///
///     HStack {
///         Button(action: goBack) { Image(systemName: "chevron.left") }
///         MinHeaderTitleView(movie.title)
///         Spacer()
///     }
///
public struct MinHeaderTitleView: View {
    private let text: String

    public init(_ text: String) {
        self.text = text
    }

    public var body: some View {
        Text(text)
            .font(.system(size: MinHeaderTitle.fontSize, weight: MinHeaderTitle.fontWeight))
            .lineLimit(1)
            .truncationMode(.tail)
    }
}
