/* AUTO-GENERATED by scripts/build-native-tokens.js — do not edit. */
/* Source: src/tokens/minTitles.js. Re-run: npm run build:native */

package com.minapps.ds.tokens

/**
 * Screen title metrics — mov min. Use with [MinPageMargins] for horizontal alignment.
 */
object MinMainContentTitle {
    const val FONT_SIZE = 48
    const val FONT_WEIGHT = 700
    const val LINE_HEIGHT_MULTIPLE = 1.2000f
    const val LETTER_SPACING = -1.2f
    const val MARGIN_BOTTOM = 16
}

object MinHomeScreenTitle {
    const val FONT_SIZE_REGULAR = 36
    const val FONT_SIZE_COMPACT = 30
    const val FONT_WEIGHT = 700
    const val LINE_HEIGHT_MULTIPLE_REGULAR = 1.2500f
    const val LINE_HEIGHT_MULTIPLE_COMPACT = 1.3000f
    const val LETTER_SPACING_REGULAR = -0.9f
    const val LETTER_SPACING_COMPACT = -0.75f
    const val MARGIN_BOTTOM = 8
}

object MinHeaderTitle {
    const val FONT_SIZE = 20
    const val FONT_WEIGHT = 600
    const val LINE_HEIGHT_MULTIPLE = 1.4000f
}
