/* AUTO-GENERATED by scripts/build-native-tokens.js — do not edit. */
/* Header bar with mov min page margins — matches web AppHeader and iOS MinAppHeaderView. */

package com.minapps.ds.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.minapps.ds.tokens.MinPageMargins
import com.minapps.ds.tokens.MinHeaderTitle

/**
 * Top bar for any min app screen. Same padding as the content area so the title
 * aligns with the page grid.
 */
@Composable
fun MinAppHeader(
    title: String,
    modifier: Modifier = Modifier,
    logo: @Composable (() -> Unit)? = null,
    actions: @Composable (RowScope.() -> Unit)? = null,
) {
    val sw = LocalConfiguration.current.screenWidthDp
    val compact = sw < 600

    val padH = if (compact) MinPageMargins.MARGIN_LEFT_MOBILE.dp else MinPageMargins.MARGIN_LEFT.dp
    val padTop = if (compact) MinPageMargins.MARGIN_TOP_MOBILE.dp else MinPageMargins.MARGIN_TOP.dp
    val padBottom = if (compact) MinPageMargins.MARGIN_BOTTOM_MOBILE.dp else MinPageMargins.MARGIN_BOTTOM.dp

    Row(
        modifier = modifier
            .fillMaxWidth()
            .padding(start = padH, end = padH, top = padTop, bottom = padBottom),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(16.dp),
        ) {
            logo?.invoke()

            Text(
                text = title,
                fontSize = MinHeaderTitle.FONT_SIZE.sp,
                fontWeight = FontWeight(MinHeaderTitle.FONT_WEIGHT),
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
            )
        }

        if (actions != null) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(12.dp),
            ) {
                actions()
            }
        }
    }
}
