// AUTO-GENERATED by scripts/build-native-tokens.js — do not edit.
// Source: src/tokens/mainLoading.js. Re-run: npm run build:native

import SwiftUI

/// Main bootstrap loading — same as WatchedIt (mov min). Leading row; do not center in full-screen `VStack`.
public enum MinMainAppLoading {
    public static let message: String = "Loading…"
    public static let spinnerDiameter: CGFloat = 14
    public static let rowGap: CGFloat = 8
    public static let labelFontSize: CGFloat = 14
    public static let paddingVertical: CGFloat = 16
}

public struct MinMainAppLoadingView: View {
    @Environment(\.horizontalSizeClass) private var horizontalSizeClass

    public init() {}

    public var body: some View {
        HStack(alignment: .center, spacing: MinMainAppLoading.rowGap) {
            ProgressView()
                .scaleEffect(0.85)
                .frame(width: MinMainAppLoading.spinnerDiameter, height: MinMainAppLoading.spinnerDiameter)
            Text(MinMainAppLoading.message)
                .font(.system(size: MinMainAppLoading.labelFontSize))
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.leading)
            Spacer(minLength: 0)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.vertical, MinMainAppLoading.paddingVertical)
        .padding(.horizontal, MinPageMargins.horizontalPadding(horizontalSizeClass: horizontalSizeClass))
        .accessibilityElement(children: .combine)
        .accessibilityLabel(MinMainAppLoading.message)
    }
}
