/* AUTO-GENERATED by scripts/build-native-tokens.js — do not edit. */
/* Source: src/tokens/mainLoading.js. Re-run: npm run build:native */

package com.minapps.ds.tokens

/**
 * Main bootstrap loading — same as WatchedIt (mov min). Start-aligned row; do not center in full-screen Column.
 */
object MinMainAppLoading {
    const val MESSAGE = "Loading…"
    const val SPINNER_SIZE_DP = 14
    const val ROW_GAP_DP = 8
    const val LABEL_FONT_SP = 14
    const val PADDING_VERTICAL_DP = 16
}
