// AUTO-GENERATED by scripts/build-native-tokens.js — do not edit.
// Source: src/tokens/spacing.js (spacing.page). Re-run: npm run build:native

import CoreGraphics

/// Page insets for every min app — same grid as WatchedIt (mov min).
/// Use for root stack padding, `UICollectionView`/`UITableView` section insets, safe-area inset stacks,
/// sticky search bars, and fixed overlay buttons so vid/pod/cyc match mov min.
public enum MinPageMargins {
    public static let marginTop: CGFloat = 24
    public static let marginBottom: CGFloat = 24
    public static let marginLeft: CGFloat = 16
    public static let marginRight: CGFloat = 16
    /// Use on compact width (< ~768pt) to match `spacing.page.*Mobile` / CSS breakpoint 767px.
    public static let marginTopMobile: CGFloat = 16
    public static let marginBottomMobile: CGFloat = 16
    public static let marginLeftMobile: CGFloat = 12
    public static let marginRightMobile: CGFloat = 12
}
