import Foundation

public enum MinIcon {
    public static let add = "plus"
    public static let close = "xmark"
    public static let checkmark = "checkmark"
    public static let edit = "pencil"
    public static let delete = "trash"
    public static let search = "magnifyingglass"
    public static let settings = "gearshape"
    public static let share = "square.and.arrow.up"
    public static let filter = "line.3.horizontal.decrease"
    public static let sort = "arrow.up.arrow.down"
    public static let chevronRight = "chevron.right"
    public static let chevronLeft = "chevron.left"
    public static let chevronDown = "chevron.down"
    public static let chevronUp = "chevron.up"
    public static let heart = "heart"
    public static let heartFill = "heart.fill"
    public static let star = "star"
    public static let starFill = "star.fill"
    public static let info = "info.circle"
    public static let warning = "exclamationmark.triangle"
    public static let error = "xmark.circle"
    public static let success = "checkmark.circle"
    public static let notification = "bell"
    public static let notificationFill = "bell.fill"
    public static let appearance = "paintbrush"
    public static let link = "link"
    public static let externalLink = "arrow.up.right.square"
    public static let safari = "safari"
    public static let play = "play.fill"
    public static let pause = "pause.fill"
}
