// AUTO-GENERATED by scripts/build-native-tokens.js — do not edit.
// Companion to MinPageMargins.swift — use so phone vs wide layouts match CSS (767px) logic.

import CoreGraphics
import SwiftUI

extension MinPageMargins {
    /// `true` when horizontal size class is compact (typical phone) — use mobile page tokens.
    public static func useCompactPageMargins(horizontalSizeClass: UserInterfaceSizeClass?) -> Bool {
        horizontalSizeClass == .compact || horizontalSizeClass == nil
    }

    /// SwiftUI horizontal inset for page content.
    public static func horizontalPadding(horizontalSizeClass: UserInterfaceSizeClass?) -> CGFloat {
        useCompactPageMargins(horizontalSizeClass: horizontalSizeClass) ? marginLeftMobile : marginLeft
    }

    public static func verticalPaddingTop(horizontalSizeClass: UserInterfaceSizeClass?) -> CGFloat {
        useCompactPageMargins(horizontalSizeClass: horizontalSizeClass) ? marginTopMobile : marginTop
    }

    public static func verticalPaddingBottom(horizontalSizeClass: UserInterfaceSizeClass?) -> CGFloat {
        useCompactPageMargins(horizontalSizeClass: horizontalSizeClass) ? marginBottomMobile : marginBottom
    }
}

#if canImport(UIKit)
import UIKit

extension MinPageMargins {
    /// UIKit: full screen content insets (mov min grid).
    public static func uiEdgeInsets(horizontalCompact: Bool) -> UIEdgeInsets {
        if horizontalCompact {
            return UIEdgeInsets(
                top: marginTopMobile,
                left: marginLeftMobile,
                bottom: marginBottomMobile,
                right: marginRightMobile
            )
        }
        return UIEdgeInsets(top: marginTop, left: marginLeft, bottom: marginBottom, right: marginRight)
    }

    /// UIKit: derive from trait collection (e.g. `view.traitCollection`).
    public static func uiEdgeInsets(traitCollection: UITraitCollection) -> UIEdgeInsets {
        uiEdgeInsets(horizontalCompact: traitCollection.horizontalSizeClass == .compact)
    }
}
#endif
