// Generated from closet_picks_snapshot.json. Do not edit by hand.
enum ClosetPicksGuestURLCatalog {
    static let urls: [String: String] = [
        "adrian utley": "https://www.criterion.com/shop/collection/648-adrian-utley-s-closet-picks",
        "agnes b": "https://www.criterion.com/shop/collection/560-agnes-b-s-closet-picks",
        "agnes varda": "https://www.criterion.com/shop/collection/472-agnes-varda-s-closet-picks",
        "agnieszka holland": "https://www.criterion.com/shop/collection/683-agnieszka-holland-s-closet-picks",
        "alan palomo": "https://www.criterion.com/shop/collection/580-alan-palomo-s-closet-picks",
        "alexander payne": "https://www.criterion.com/shop/collection/478-alexander-payne-s-closet-picks",
        "alfonso cuaron and pawel pawlikowski": "https://www.criterion.com/shop/collection/526-alfonso-cuaron-and-pawel-pawlikowski-s-closet-picks",
        "alicia malone": "https://www.criterion.com/shop/collection/457-alicia-malone-s-closet-picks",
        "amelia dimoldenberg": "https://www.criterion.com/shop/collection/734-amelia-dimoldenberg-s-closet-picks",
        "amy heckerling": "https://www.criterion.com/shop/collection/465-amy-heckerling-s-closet-picks",
        "andre holland": "https://www.criterion.com/shop/collection/745-andre-holland-s-closet-picks",
        "andrew garfield": "https://www.criterion.com/shop/collection/730-andrew-garfield-s-closet-picks",
        "andrew stanton": "https://www.criterion.com/shop/collection/761-andrew-stanton-s-closet-picks",
        "anna karina": "https://www.criterion.com/shop/collection/451-anna-karina-s-closet-picks",
        "anna kendrick": "https://www.criterion.com/shop/collection/729-anna-kendrick-s-closet-picks",
        "annie baker and lucian johnston": "https://www.criterion.com/shop/collection/662-annie-baker-and-lucian-johnston-s-closet-picks",
        "ari aster": "https://www.criterion.com/shop/collection/544-ari-aster-s-closet-picks",
        "asif kapadia": "https://www.criterion.com/shop/collection/462-asif-kapadia-s-closet-picks",
        "aubrey plaza and jeff baena": "https://www.criterion.com/shop/collection/474-aubrey-plaza-and-jeff-baena-s-closet-picks",
        "ayo edebiri": "https://www.criterion.com/shop/collection/666-ayo-edebiri-s-closet-picks",
        "barry jenkins": "https://www.criterion.com/shop/collection/470-barry-jenkins-s-closet-picks",
        "barry levinson": "https://www.criterion.com/shop/collection/475-barry-levinson-s-closet-picks",
        "barry sonnenfeld": "https://www.criterion.com/shop/collection/752-barry-sonnenfeld-s-closet-picks",
        "ben gibbards": "https://www.criterion.com/shop/collection/638-ben-gibbards-s-closet-picks",
        "ben sinclair": "https://www.criterion.com/shop/collection/424-ben-sinclair-s-closet-picks",
        "ben wheatley": "https://www.criterion.com/shop/collection/471-ben-wheatley-s-closet-picks",
        "benjamin millepied": "https://www.criterion.com/shop/collection/550-benjamin-millepied-s-closet-picks",
        "bertrand bonello": "https://www.criterion.com/shop/collection/640-bertrand-bonello-s-closet-picks",
        "bill and turner ross": "https://www.criterion.com/shop/collection/667-bill-and-turner-ross-s-closet-picks",
        "bill hader": "https://www.criterion.com/shop/collection/720-bill-hader-s-closet-picks",
        "bill pope": "https://www.criterion.com/shop/collection/663-bill-pope-s-closet-picks",
        "bong joon ho": "https://www.criterion.com/shop/collection/530-bong-joon-ho-s-closet-picks",
        "brit marling and zal batmanglij": "https://www.criterion.com/shop/collection/611-brit-marling-and-zal-batmanglij-s-closet-picks",
        "callum turner": "https://www.criterion.com/shop/collection/641-callum-turner-s-closet-picks",
        "carl franklin": "https://www.criterion.com/shop/collection/552-carl-franklin-s-closet-picks",
        "carol kane": "https://www.criterion.com/shop/collection/676-carol-kane-s-closet-picks",
        "cate blanchett and todd field": "https://www.criterion.com/shop/collection/486-cate-blanchett-and-todd-field-s-closet-picks",
        "catherine breillat": "https://www.criterion.com/shop/collection/664-catherine-breillat-s-closet-picks",
        "cauleen smith": "https://www.criterion.com/shop/collection/535-cauleen-smith-s-closet-picks",
        "charles melton": "https://www.criterion.com/shop/collection/621-charles-melton-s-closet-picks",
        "charlie day": "https://www.criterion.com/shop/collection/548-charlie-day-s-closet-picks",
        "charlotte gainsbourg": "https://www.criterion.com/shop/collection/482-charlotte-gainsbourg-s-closet-picks",
        "charlotte rampling and andrew haigh": "https://www.criterion.com/shop/collection/464-charlotte-rampling-and-andrew-haigh-s-closet-picks",
        "charlotte wells": "https://www.criterion.com/shop/collection/520-charlotte-wells-s-closet-picks",
        "chelsea peretti": "https://www.criterion.com/shop/collection/636-chelsea-peretti-s-closet-picks",
        "cheryl dunye": "https://www.criterion.com/shop/collection/653-cheryl-dunye-s-closet-picks",
        "chris eigeman": "https://www.criterion.com/shop/collection/452-chris-eigeman-s-closet-picks",
        "claire denis": "https://www.criterion.com/shop/collection/428-claire-denis-closet-picks",
        "colin quinn": "https://www.criterion.com/shop/collection/426-colin-quinn-s-closet-picks",
        "cristian mungiu": "https://www.criterion.com/shop/collection/461-cristian-mungiu-s-closet-picks",
        "dan levy": "https://www.criterion.com/shop/collection/619-dan-levy-s-closet-picks",
        "desiree akhavan": "https://www.criterion.com/shop/collection/435-desiree-akhavan-s-closet-picks",
        "devo gerald casale and mark mothersbaugh": "https://www.criterion.com/shop/collection/660-devo-gerald-casale-and-mark-mothersbaugh-s-closet-picks",
        "dylan baker": "https://www.criterion.com/shop/collection/721-dylan-baker-s-closet-picks",
        "elegance bratton": "https://www.criterion.com/shop/collection/519-elegance-bratton-s-closet-picks",
        "ethan hawke and jonathan marc sherman": "https://www.criterion.com/shop/collection/446-ethan-hawke-and-jonathan-marc-sherman-s-closet-picks",
        "euzhan palcy": "https://www.criterion.com/shop/collection/440-euzhan-palcy-s-closet-picks",
        "five comics": "https://www.criterion.com/shop/collection/443-five-comics-closet-picks",
        "floyd norman": "https://www.criterion.com/shop/collection/527-floyd-norman-s-closet-picks",
        "flying lotus": "https://www.criterion.com/shop/collection/438-flying-lotus-s-closet-picks",
        "francis ford coppola": "https://www.criterion.com/shop/collection/763-francis-ford-coppola-s-closet-picks",
        "gael garcia bernal": "https://www.criterion.com/shop/collection/616-gael-garcia-bernal-s-closet-picks",
        "garrett bradley": "https://www.criterion.com/shop/collection/481-garrett-bradley-s-closet-picks",
        "gaspar noe": "https://www.criterion.com/shop/collection/432-gaspar-noe-s-closet-picks",
        "gina gershon": "https://www.criterion.com/shop/collection/671-gina-gershon-s-closet-picks",
        "gina prince bythewood": "https://www.criterion.com/shop/collection/492-gina-prince-bythewood-s-closet-picks",
        "gints zilbalodis": "https://www.criterion.com/shop/collection/751-gints-zilbalodis-s-closet-picks",
        "greg gonzalez": "https://www.criterion.com/shop/collection/685-greg-gonzalez-s-closet-picks",
        "gregg araki": "https://www.criterion.com/shop/collection/554-gregg-araki-s-closet-picks",
        "guillermo del toro": "https://www.criterion.com/shop/collection/645-guillermo-del-toro-s-closet-picks",
        "guy maddin": "https://www.criterion.com/shop/collection/598-guy-maddin-s-closet-picks",
        "hari nef": "https://www.criterion.com/shop/collection/594-hari-nef-s-closet-picks",
        "harris savides": "https://www.criterion.com/shop/collection/599-harris-savides-s-closet-picks",
        "hideo kojima": "https://www.criterion.com/shop/collection/579-hideo-kojima-s-closet-picks",
        "hlynur palmason": "https://www.criterion.com/shop/collection/612-hlynur-palmason-s-closet-picks",
        "ira sachs": "https://www.criterion.com/shop/collection/600-ira-sachs-s-closet-picks",
        "isabel sandoval": "https://www.criterion.com/shop/collection/441-isabel-sandoval-s-closet-picks",
        "isabelle huppert": "https://www.criterion.com/shop/collection/741-isabelle-huppert-s-closet-picks",
        "jacqueline novak and john early": "https://www.criterion.com/shop/collection/449-jacqueline-novak-and-john-early-s-closet-picks",
        "james l brooks": "https://www.criterion.com/shop/collection/437-james-l-brooks-s-closet-picks",
        "jane schoenbrun": "https://www.criterion.com/shop/collection/658-jane-schoenbrun-s-closet-picks",
        "janelle monae": "https://www.criterion.com/shop/collection/733-janelle-monae-s-closet-picks",
        "jarvis cocker": "https://www.criterion.com/shop/collection/748-jarvis-cocker-s-closet-picks",
        "jason schwartzman": "https://www.criterion.com/shop/collection/595-jason-schwartzman-s-closet-picks",
        "jean pierre and luc dardenne": "https://www.criterion.com/shop/collection/565-jean-pierre-and-luc-dardenne-s-closet-picks",
        "jenni olson": "https://www.criterion.com/shop/collection/430-jenni-olson-s-closet-picks",
        "jennifer kent": "https://www.criterion.com/shop/collection/726-jennifer-kent-s-closet-picks",
        "jeremy o harris": "https://www.criterion.com/shop/collection/661-jeremy-o-harris-s-closet-picks",
        "jeremy pope": "https://www.criterion.com/shop/collection/736-jeremy-pope-s-closet-picks",
        "jeremy thomas": "https://www.criterion.com/shop/collection/673-jeremy-thomas-s-closet-picks",
        "jerry schatzberg": "https://www.criterion.com/shop/collection/681-jerry-schatzberg-s-closet-picks",
        "jerzy skolimowski": "https://www.criterion.com/shop/collection/513-jerzy-skolimowski-s-closet-picks",
        "joachim trier": "https://www.criterion.com/shop/collection/453-joachim-trier-s-closet-picks",
        "joanna hogg": "https://www.criterion.com/shop/collection/419-joanna-hogg-s-closet-picks",
        "joel edgerton": "https://www.criterion.com/shop/collection/626-joel-edgerton-s-closet-picks",
        "joel kim booster": "https://www.criterion.com/shop/collection/637-joel-kim-booster-s-closet-picks",
        "john darnielle": "https://www.criterion.com/shop/collection/521-john-darnielle-s-closet-picks",
        "john dwyer": "https://www.criterion.com/shop/collection/433-john-dwyer-s-closet-picks",
        "john sayles": "https://www.criterion.com/shop/collection/429-john-sayles-s-closet-picks",
        "john waters": "https://www.criterion.com/shop/collection/422-john-waters-closet-picks",
        "johnnie to": "https://www.criterion.com/shop/collection/746-johnnie-to-s-closet-picks",
        "josh and benny safdie": "https://www.criterion.com/shop/collection/476-josh-and-benny-safdie-s-closet-picks",
        "jr": "https://www.criterion.com/shop/collection/725-jr-s-closet-picks",
        "jude law": "https://www.criterion.com/shop/collection/684-jude-law-s-closet-picks",
        "juliette binoche and ralph fiennes": "https://www.criterion.com/shop/collection/765-juliette-binoche-and-ralph-fiennes-s-closet-picks",
        "karina longworth": "https://www.criterion.com/shop/collection/455-karina-longworth-s-closet-picks",
        "kerry condon": "https://www.criterion.com/shop/collection/644-kerry-condon-s-closet-picks",
        "kevin smith": "https://www.criterion.com/shop/collection/760-kevin-smith-s-closet-picks",
        "kim cattrall": "https://www.criterion.com/shop/collection/431-kim-cattrall-s-closet-picks",
        "kleber mendonca filho": "https://www.criterion.com/shop/collection/624-kleber-mendonca-filho-s-closet-picks",
        "koji yakusho": "https://www.criterion.com/shop/collection/668-koji-yakusho-s-closet-picks",
        "kyle maclachlan": "https://www.criterion.com/shop/collection/487-kyle-maclachlan-s-closet-picks",
        "laura albert jeff feuerzeig": "https://www.criterion.com/shop/collection/479-laura-albert-jeff-feuerzeig-s-closet-picks",
        "laurie anderson": "https://www.criterion.com/shop/collection/463-laurie-anderson-s-closet-picks",
        "lee daniels": "https://www.criterion.com/shop/collection/682-lee-daniels-s-closet-picks",
        "leslie harris": "https://www.criterion.com/shop/collection/454-leslie-harris-s-closet-picks",
        "lila aviles": "https://www.criterion.com/shop/collection/620-lila-aviles-s-closet-picks",
        "lily gladstone erica tremblay": "https://www.criterion.com/shop/collection/674-lily-gladstone-erica-tremblay-s-closet-picks",
        "lina rodriguez": "https://www.criterion.com/shop/collection/625-lina-rodriguez-s-closet-picks",
        "louis garrel": "https://www.criterion.com/shop/collection/537-louis-garrel-s-closet-picks",
        "lucrecia martel": "https://www.criterion.com/shop/collection/439-lucrecia-martel-s-closet-picks",
        "luis guzman": "https://www.criterion.com/shop/collection/585--luis-guzman-s-closet-picks",
        "m i a and stephen loveridge": "https://www.criterion.com/shop/collection/423-m-i-a-and-stephen-loveridge-s-closet-picks",
        "manuel garcia rulfo": "https://www.criterion.com/shop/collection/651-manuel-garcia-rulfo-s-closet-picks",
        "marc maron": "https://www.criterion.com/shop/collection/509-marc-maron-s-closet-picks",
        "marco bellocchio": "https://www.criterion.com/shop/collection/445-marco-bellocchio-s-closet-picks",
        "marianne jean baptiste mike leigh": "https://www.criterion.com/shop/collection/749-marianne-jean-baptiste-mike-leigh-s-closet-picks",
        "mark bridges": "https://www.criterion.com/shop/collection/592-mark-bridges-s-closet-picks",
        "mary harron": "https://www.criterion.com/shop/collection/569-mary-harron-s-closet-picks",
        "matias pineiro": "https://www.criterion.com/shop/collection/473-matias-pineiro-s-closet-picks",
        "matteo garrone": "https://www.criterion.com/shop/collection/633-matteo-garrone-s-closet-picks",
        "matthew modine": "https://www.criterion.com/shop/collection/436-matthew-modine-s-closet-picks",
        "maya and ethan hawke": "https://www.criterion.com/shop/collection/647-maya-and-ethan-hawke-s-closet-picks",
        "michael cera": "https://www.criterion.com/shop/collection/491-michael-cera-s-closet-picks",
        "michael k williams": "https://www.criterion.com/shop/collection/602-michael-k-williams-s-closet-picks",
        "michael shannon": "https://www.criterion.com/shop/collection/556-michael-shannon-s-closet-picks",
        "mike leigh": "https://www.criterion.com/shop/collection/538-mike-leigh-s-closet-picks",
        "minnie driver": "https://www.criterion.com/shop/collection/539-minnie-driver-s-closet-picks",
        "molly ringwald": "https://www.criterion.com/shop/collection/639-molly-ringwald-s-closet-picks",
        "nathalie emmanuel": "https://www.criterion.com/shop/collection/738-nathalie-emmanuel-s-closet-picks",
        "nathan lane": "https://www.criterion.com/shop/collection/427-nathan-lane-s-closet-picks",
        "neal brennan": "https://www.criterion.com/shop/collection/628-neal-brennan-s-closet-picks",
        "nicolas winding refn": "https://www.criterion.com/shop/collection/541-nicolas-winding-refn-s-closet-picks",
        "norman reedus": "https://www.criterion.com/shop/collection/758-norman-reedus-s-closet-picks",
        "nuri bilge ceylan": "https://www.criterion.com/shop/collection/630-nuri-bilge-ceylan-s-closet-picks",
        "owen kline": "https://www.criterion.com/shop/collection/485-owen-kline-s-closet-picks",
        "pamela anderson": "https://www.criterion.com/shop/collection/757-pamela-anderson-s-closet-picks",
        "park chan wook": "https://www.criterion.com/shop/collection/575-park-chan-wook-s-closet-picks",
        "patrick brice": "https://www.criterion.com/shop/collection/603-patrick-brice-s-closet-picks",
        "patton oswalt": "https://www.criterion.com/shop/collection/576-patton-oswalt-s-closet-picks",
        "paul b preciado": "https://www.criterion.com/shop/collection/588-paul-b-preciado-s-closet-picks",
        "paul dano": "https://www.criterion.com/shop/collection/447-paul-dano-s-closet-picks",
        "paul giamatti": "https://www.criterion.com/shop/collection/631-paul-giamatti-s-closet-picks",
        "paul scheer": "https://www.criterion.com/shop/collection/672-paul-scheer-s-closet-picks",
        "pauline chalamet": "https://www.criterion.com/shop/collection/536-pauline-chalamet-s-closet-picks",
        "payal kapadia": "https://www.criterion.com/shop/collection/737-payal-kapadia-s-closet-picks",
        "peter sarsgaard": "https://www.criterion.com/shop/collection/434-peter-sarsgaard-s-closet-picks",
        "phil rosenthal": "https://www.criterion.com/shop/collection/469-phil-rosenthal-s-closet-picks",
        "philip kaufman": "https://www.criterion.com/shop/collection/606-philip-kaufman-s-closet-picks",
        "ramell ross": "https://www.criterion.com/shop/collection/756-ramell-ross-s-closet-picks",
        "raul castillo": "https://www.criterion.com/shop/collection/561-raul-castillo-s-closet-picks",
        "raven jackson": "https://www.criterion.com/shop/collection/590-raven-jackson-s-closet-picks",
        "rebecca miller": "https://www.criterion.com/shop/collection/582-rebecca-miller-s-closet-picks",
        "renate reinsve": "https://www.criterion.com/shop/collection/484-renate-reinsve-s-closet-picks",
        "richard ayoade": "https://www.criterion.com/shop/collection/540-richard-ayoade-s-closet-picks",
        "richard e grant": "https://www.criterion.com/shop/collection/425-richard-e-grant-s-closet-picks",
        "rickie lee jones": "https://www.criterion.com/shop/collection/564-rickie-lee-jones-s-closet-picks",
        "rodarte": "https://www.criterion.com/shop/collection/420-rodarte-s-closet-picks",
        "roger corman": "https://www.criterion.com/shop/collection/584-roger-corman-s-closet-picks",
        "roger james deakins": "https://www.criterion.com/shop/collection/566-roger-james-deakins-s-closet-picks",
        "rosine mbakam": "https://www.criterion.com/shop/collection/622-rosine-mbakam-s-closet-picks",
        "ryusuke hamaguchi": "https://www.criterion.com/shop/collection/652-ryusuke-hamaguchi-s-closet-picks",
        "sarita choudhury": "https://www.criterion.com/shop/collection/483-sarita-choudhury-s-closet-picks",
        "saul williams and anisia uzeyman": "https://www.criterion.com/shop/collection/494-saul-williams-and-anisia-uzeyman-s-closet-picks",
        "sean baker": "https://www.criterion.com/shop/collection/458-sean-baker-s-closet-picks",
        "slavoj zizek": "https://www.criterion.com/shop/collection/609-slavoj-zizek-s-closet-picks",
        "st vincent": "https://www.criterion.com/shop/collection/642-st-vincent-s-closet-picks",
        "tavi gevinson": "https://www.criterion.com/shop/collection/448-tavi-gevinson-s-closet-picks",
        "terry gilliam": "https://www.criterion.com/shop/collection/442-terry-gilliam-s-closet-picks",
        "the quay brothers": "https://www.criterion.com/shop/collection/597-the-quay-brothers-closet-picks",
        "the wolfpack": "https://www.criterion.com/shop/collection/607-the-wolfpack-s-closet-picks",
        "theodore witcher": "https://www.criterion.com/shop/collection/480-theodore-witcher-s-closet-picks",
        "tim blake nelson": "https://www.criterion.com/shop/collection/659-tim-blake-nelson-s-closet-picks",
        "tim robbins": "https://www.criterion.com/shop/collection/466-tim-robbins-s-closet-picks",
        "todd haynes": "https://www.criterion.com/shop/collection/591-todd-haynes-s-closet-picks",
        "trace lysette": "https://www.criterion.com/shop/collection/555-trace-lysette-s-closet-picks",
        "tyler mitchell": "https://www.criterion.com/shop/collection/589-tyler-mitchell-s-closet-picks",
        "udo kier": "https://www.criterion.com/shop/collection/581-udo-kier-s-closet-picks",
        "viggo mortensen": "https://www.criterion.com/shop/collection/670-viggo-mortensen-s-closet-picks",
        "volker schlondorff": "https://www.criterion.com/shop/collection/610-volker-schlondorff-s-closet-picks",
        "wilco": "https://www.criterion.com/shop/collection/493-wilco-s-closet-picks",
        "willem dafoe": "https://www.criterion.com/shop/collection/618-willem-dafoe-s-closet-picks",
        "william friedkin": "https://www.criterion.com/shop/collection/542-william-friedkin-s-closet-picks",
        "wim wenders": "https://www.criterion.com/shop/collection/634-wim-wenders-closet-picks",
        "winona ryder": "https://www.criterion.com/shop/collection/677-winona-ryder-s-closet-picks",
        "yo la tengo": "https://www.criterion.com/shop/collection/557-yo-la-tengo-s-closet-picks",
        "yorgos lanthimos ariane labed": "https://www.criterion.com/shop/collection/467-yorgos-lanthimos-ariane-labed-s-closet-picks",
        "zoe kravitz and channing tatum": "https://www.criterion.com/shop/collection/675-zoe-kravitz-and-channing-tatum-s-closet-picks"
    ]
}
